### ISSUE TITLE
Не работает авторизация

### ISSUE THREAD

**Issue by evgenybozhko2** [VKCOM/superappkit-android-demo#19]
Версия 
   implementation 'com.vk:oauth-vk:0.111-24428'
   implementation 'com.vk:vksdk-pub:0.112-24430'
    
Предыдущая версия работала но потому что-то изменили на сервере. Если не ошибаюсь. Спасибо!    

    

> `FATAL EXCEPTION: main
> Process: packagename, PID: 12524
> java.lang.RuntimeException: Unable to start activity ComponentInfo{packagename/com.vk.auth.main.VkClientAuthActivity$OauthActivity}: java.lang.reflect.InvocationTargetException
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
>     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>     at android.os.Handler.dispatchMessage(Handler.java:107)
>     at android.os.Looper.loop(Looper.java:214)
>     at android.app.ActivityThread.main(ActivityThread.java:7356)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> Caused by: java.lang.reflect.InvocationTargetException
>     at java.lang.reflect.Constructor.newInstance0(Native Method)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
>     at com.vk.auth.oauth.provider.ReflectionBasedOAuthProviderFactory.create(SourceFile:9)
>     at com.vk.auth.oauth.VkOAuthServicePresenter.<init>(SourceFile:9)
>     at com.vk.auth.oauth.VkOauthActivityDelegate.onCreateInternal(SourceFile:6)
>     at com.vk.auth.DefaultAuthActivity.onCreateInternal(SourceFile:7)
>     at com.vk.auth.DefaultAuthActivity.onCreate(SourceFile:42)
>     at android.app.Activity.performCreate(Activity.java:7802)
>     at android.app.Activity.performCreate(Activity.java:7791)
>     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
>     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
>     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
>     at android.os.Handler.dispatchMessage(Handler.java:107) 
>     at android.os.Looper.loop(Looper.java:214) 
>     at android.app.ActivityThread.main(ActivityThread.java:7356) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
> Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/vk/auth/commonerror/CommonApiErrorHandler;
>     at java.lang.Class.classForName(Native Method)
>     at java.lang.Class.forName(Class.java:454)
>     at java.lang.Class.forName(Class.java:379)
>     at com.vk.auth.oauth.provider.ReflectionBasedOAuthProviderFactory.create(SourceFile:7)
>     at com.vk.auth.oauth.VkOAuthServicePresenter.<init>(SourceFile:9) 
>     at com.vk.auth.oauth.VkOauthActivityDelegate.onCreateInternal(SourceFile:6) 
>     at com.vk.auth.DefaultAuthActivity.onCreateInternal(SourceFile:7) 
>     at com.vk.auth.DefaultAuthActivity.onCreate(SourceFile:42) 
>     at android.app.Activity.performCreate(Activity.java:7802) 
>     at android.app.Activity.performCreate(Activity.java:7791) 
>     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
>     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
>     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
>     at android.os.Handler.dispatchMessage(Handler.java:107) 
>     at android.os.Looper.loop(Looper.java:214) 
>     at android.app.ActivityThread.main(ActivityThread.java:7356) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vk.auth.commonerror.CommonApiErrorHandler" on path: DexPathList[[zip file
> "/data/app/packagename-2A3nuj2ruR9pPT_ZygNFNw==/base.apk"],nativeLibraryDirectories=[/data/app/packagename-2A3nuj2ruR9pPT_ZygNFNw==/lib/x86, /data/app/packagename-2A3nuj2ruR9pPT_ZygNFNw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
>     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>     at java.lang.Class.classForName(Native Method) 
>     at java.lang.Class.forName(Class.java:454) 
>     at java.lang.Class.forName(Class.java:379) 
>     at com.vk.auth.oauth.provider.ReflectionBasedOAuthProviderFactory.create(SourceFile:7) 
>     at com.vk.auth.oauth.VkOAuthServicePresenter.<init>(SourceFile:9) 
>     at com.vk.auth.oauth.VkOauthActivityDelegate.onCreateInternal(SourceFile:6) 
>     at com.vk.auth.DefaultAuthActivity.onCreateInternal(SourceFile:7) 
>     at com.vk.auth.DefaultAuthActivity.onCreate(SourceFile:42) 
>     at android.app.Activity.performCreate(Activity.java:7802) 
>     at android.app.Activity.performCreate(Activity.java:7791) 
>     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
>     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
>     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
>     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
>     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
>     at android.os.Handler.dispatchMessage(Handler.java:107) 
>     at android.os.Looper.loop(Looper.java:214) 
>     at android.app.ActivityThread.main(ActivityThread.java:7356) 
>     at java.lang.reflect.Method.invoke(Native Method) 
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by inoplanetyaninNikita** [comment]
Версии com.vk:oauth-vk и vk:vksdk-pub должны совпадать, Вы можете посмотреть их тут:

https://artifactory-external.vkpartner.ru/ui/native/superappkit-maven-public/com/vk/vksdk-pub/
https://artifactory-external.vkpartner.ru/ui/native/superappkit-maven-public/com/vk/oauth-vk/

**Comment by VPNSatoshi** [comment]
Такая же проблема!

**Comment by evgenybozhko2** [comment]
> Версии com.vk:oauth-vk и vk:vksdk-pub должны совпадать, Вы можете посмотреть их тут:
> 
> https://artifactory-external.vkpartner.ru/ui/native/superappkit-maven-public/com/vk/vksdk-pub/ https://artifactory-external.vkpartner.ru/ui/native/superappkit-maven-public/com/vk/oauth-vk/

Спасибо за замечание. Пробовали делать с разными моментами. Все равно имеем такую картину!

Прикрепил полный лог от инциализации до ошибки 
![Screenshot 2023-10-19 at 15 58 21](https://github.com/VKCOM/superappkit-android-demo/assets/5464497/a127595d-8e0f-4773-a779-ac73ca387707)
[vk_login.txt](https://github.com/VKCOM/superappkit-android-demo/files/13043012/vk_login.txt)

**Comment by inoplanetyaninNikita** [comment]
Вам тут пишут ошибку : One of the parameters specified was missing or invalid: app is not
found, можете показать ваши ресурсы связанные с ВК и билд градл

**Comment by evgenybozhko2** [comment]
> Вам тут пишут ошибку : One of the parameters specified was missing or invalid: app is not found, можете показать ваши ресурсы связанные с ВК и билд градл

Да. Но только дело в том, что авторизация работала, а потом в один день случилась такая ошибка без изменений. Выглядит как изменения со стороны сервера. 

`   manifestPlaceholders = [
                    'VkExternalAuthRedirectScheme' : 'vk' + properties['VK_APP_ID'],
                    'VkExternalAuthRedirectHost' : 'vk.com',
            ]`

`   <string name="vk_client_secret" translatable="false">xxxxxx</string>
    <string name="vk_external_oauth_redirect_url" translatable="false">vk51735321://vk.com</string>
    <string name="vk_account_manager_id" translatable="false">com.xxx.xxx.account</string>`

` <integer name="com_vk_sdk_AppId">51735321</integer>`

**Comment by garik-code** [comment]
Такая же проблема

**Comment by evgenybozhko2** [comment]
Решилось пересозданием приложения по инструкции https://id.vk.com/business/go/docs/vkid/1.60.0/create-application
